#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layer_number {
  _BASE = 0,
  _QRTY,
  _CLMK,
  _SYMB,
  _NAVI ,
  _NUMP,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_BASE] = LAYOUT( \
      /* _______ , _______ , _______ , _______ , _______ , _______   , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , */
      KC_GESC    , KC_1    , KC_2    , KC_3    , KC_4    , KC_5      , KC_NO   , KC_NO   , KC_6    , KC_7    , KC_8    , KC_9    , KC_0    , KC_NO   , \
      KC_TAB     , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO     , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
      KC_LCTL    , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO     , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_BSPC , \
      KC_LSFT    , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO     , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
      MO(5)      , KC_LGUI , KC_LALT , KC_LGUI , MO(3)   , KC_SPC    , KC_DEL  , KC_SPC  , KC_ENT  , MO(4)   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
                                                           KC_SPC    , KC_DEL  , KC_SPC  , KC_ENT \
      ),
  [_QRTY] = LAYOUT( \
      /* _______  , _______ , _______ , _______ , _______ , _______    , _______ , _______ , _______  , _______ , _______ , _______ , _______ , _______ , */
      KC_TRNS     , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS    , KC_TRNS , KC_TRNS , KC_TRNS  , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , \
      KC_TRNS     , KC_Q    , KC_W    , KC_E    , KC_R    , KC_T       , KC_TRNS , KC_TRNS , KC_Y     , KC_U    , KC_I    , KC_O    , KC_P    , KC_TRNS , \
      KC_TRNS     , KC_A    , KC_S    , KC_D    , KC_F    , KC_G       , KC_TRNS , KC_TRNS , KC_H     , KC_J    , KC_K    , KC_L    , KC_SCLN , KC_TRNS , \
      KC_TRNS     , KC_Z    , KC_X    , KC_C    , KC_V    , KC_B       , KC_TRNS , KC_TRNS , KC_N     , KC_M    , KC_COMM , KC_DOT  , KC_SLSH , KC_TRNS , \
      KC_TRNS     , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS    , KC_TRNS , KC_TRNS , KC_TRNS  , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , \
       /* _______ , _______ , _______ , _______ , _______ , */ KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS) ,
  [_CLMK] = LAYOUT( \
      /* _______ , _______ , _______ , _______ , _______ , _______    , _______ , _______ , _______  , _______ , _______ , _______ , _______ , _______ , */
      KC_TRNS    , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS    , KC_TRNS , KC_TRNS , KC_TRNS  , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , \
      KC_TRNS    , KC_Q    , KC_W    , KC_F    , KC_P    , KC_B       , KC_TRNS , KC_TRNS , KC_J     , KC_L    , KC_U    , KC_Y    , KC_SCLN , KC_TRNS , \
      KC_TRNS    , KC_A    , KC_R    , KC_S    , KC_T    , KC_G       , KC_TRNS , KC_TRNS , KC_M     , KC_N    , KC_E    , KC_I    , KC_O    , KC_TRNS , \
      KC_TRNS    , KC_Z    , KC_X    , KC_C    , KC_D    , KC_V       , KC_TRNS , KC_TRNS , KC_K     , KC_H    , KC_COMM , KC_DOT  , KC_SLSH , KC_TRNS , \
      KC_TRNS    , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS    , KC_TRNS , KC_TRNS , KC_TRNS  , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS , \
      /* _______ , _______ , _______ , _______ , _______ , */ KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS) ,
  [_SYMB] = LAYOUT( \
      /* _______ , _______ , _______ , _______ , _______ , _______     , _______ , _______ , _______  , _______ , _______ , _______ , _______ , _______ , */
      KC_TILD    , KC_EXLM , KC_AT   , KC_HASH , KC_DLR  , KC_PERC     , KC_NO   , KC_NO   , KC_CIRC  , KC_AMPR , KC_ASTR , KC_LPRN , KC_RPRN , KC_NO   , \
      KC_NO      , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO       , KC_NO   , KC_NO   , KC_LCBR  , KC_RCBR , KC_LBRC , KC_RBRC , KC_BSLS , KC_NO   , \
      KC_TRNS    , KC_TILD , KC_MINS , KC_PLUS , KC_EQL  , KC_NO       , KC_NO   , DF(2)   , KC_NO    , KC_LPRN , KC_RPRN , KC_DQUO , KC_QUOT , KC_TRNS , \
      KC_TRNS    , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO       , RESET   , DF(1)   , KC_NO    , KC_UNDS , KC_LT   , KC_GT   , KC_PIPE , RGB_TOG , \
      KC_NO      , KC_NO   , KC_TRNS , KC_NO   , KC_TRNS , KC_TRNS     , KC_TRNS , KC_TRNS , KC_TRNS  , KC_TRNS , KC_NO   , KC_NO   , KC_NO   , RGB_MOD , \
      /* _______ , _______ , _______ , _______ , _______ , */  KC_TRNS , KC_TRNS , KC_TRNS , KC_TRNS) ,
  [_NAVI] = LAYOUT( \
      /* _______ , _______ , _______ , _______ , _______ , _______  , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , */
      KC_NO      , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO    , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
      KC_NO      , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO    , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
      KC_NO      , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO    , KC_NO   , KC_NO   , KC_LEFT , KC_DOWN , KC_UP   , KC_RGHT , KC_NO   , KC_NO   , \
      KC_NO      , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO    , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
      KC_NO      , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO    , KC_NO   , KC_NO   , KC_NO   , KC_TRNS , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
 /* _______      , _______ , _______ , _______ , _______ , */ KC_NO , KC_NO   , KC_NO   , KC_NO)  ,
  [_NUMP] = LAYOUT( \
      /* _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , _______ , */
      KC_NO      , KC_F1   , KC_F2   , KC_F3   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_PAST , KC_P7   , KC_P8   , KC_P9   , KC_PMNS , KC_NO   , \
      KC_NO      , KC_F4   , KC_F5   , KC_F6   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_PSLS , KC_P4   , KC_P5   , KC_P6   , KC_PPLS , KC_NO   , \
      KC_NO      , KC_F7   , KC_F8   , KC_F9   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_P1   , KC_P2   , KC_P3   , KC_NO   , KC_NO   , \
      KC_NO      , KC_F10  , KC_F11  , KC_F12  , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_P0   , KC_PDOT , KC_PENT , KC_PEQL , KC_NO   , \
      KC_TRNS    , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   , \
 /* _______      , _______ , _______ , _______ , _______ , */ KC_NO , KC_NO   , KC_NO   , KC_NO)
};

